### ISSUE TITLE
Singularity error and parameter selection

### ISSUE THREAD

**Issue by hurazh** [carter-allen/spruce#1]
Hi Carter,

When I tested on one of my datasets, I got singularity errors on multiple `solve()` functions in `fit_mvn_PG_smooth`.  It turned out that I can fix most of them by just applying diagonal perturbation. However, it does not work for the one in `line 103`. Any idea of how to fix that?

Also, as mentioned in the paper, you are selecting the optimal `K` by WAIC. Do you have some function in the package to do model selection or calculate WAIC of your fitted models?

**Comment by carter-allen** [comment]
Hi, thank you for the feedback! We’ve found the singularity issue with the mixture component covariance matrices sometimes occurs when the MCMC approaches or hits some boundary condition (like empty or sparsely populated mixture components). We’re working to make the sampler more robust to avoid or better deal with these boundary cases automatically.

Regarding WAIC, we are working on integrating that into an overall more unified user interface, so that WAIC will simply be returned as a value within the model fit object.

We appreciate your patience as we work on turning this crude development version into a more full functioning package. I will respond here with updates in the near future!

**Comment by bayesbm** [comment]
Dear Dr. Allen,

For a my master's thesis, I am working with SPRUCE as well. After getting in touch with Professor Neelon, he replied that I might get in touch with you through GitHub.I have the same question as above. Do you have an update on the model selection code? Would you be able to share it perhaps? A crude version would also be greatly appreciated. 

Also, working with your software has been a pleasure so far. And I am very impressed by how quick the Gibbs sampler is. I tried fitting a similar model using INLA, but did not manage to get anywhere near the performance.

Yours sincerely,

Bas Matsuura
Leiden University, The Netherlands

**Comment by bayesbm** [comment]
Dear Dr. Allen,

Just another question. As I understand it, the fit_msn_pg_smooth() function should fit the model described in the Gibbs sampler of the appendix. At least, this is the most complex model of the MSN models on GitHub. Yet I don't see a call to the C++ helper function to for the MCAR spatial effect, update_phi_spot_MCAR, in that script. There is a call to update_z_MSN_PG_smooth, but this function does not incorporate the MCAR either. As a last indicator, there's no MCAR in the name of the file. None of the MSN R.files contain this term.

Which function in the SPRUCE package and/or on GitHub is supposed to fit the complete model as described in Web Appendix B? None of them appear to check all the boxes. Probably I just overlooked it or misunderstand something about the inner workings of the algorithm. Thank you again in advance.

Yours sincerely,

Bas Matsuura

**Comment by carter-allen** [comment]
Hi, in order to offer better stability of the Gibbs sampler, the model you describe has been deprecated in favor of simpler versions for real world analyses. For best stability, I would recommend to use the MVN versions with or without spatial terms for analyses of principal component features. The full-featured model could be potentially re-visited for simulations or small data applications as done in the paper to improve stability, but unfortunately I am not able to add to or maintain the package due to a change in my professional responsibilities.

**Comment by bayesbm** [comment]
Thank you for the explanation. I will try out the MVN versions and try to implement the WAIC computation for them. All the post-burn-in iterations are already saved in the final list, so it should be manageable. All the best!
